name: Deploy to RumahWeb

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mbstring, xml, ctype, iconv, intl, pdo_mysql, dom, filter, gd, iconv, json, mbstring, pdo, phar, tokenizer, xml, zip
        coverage: none
        
    - name: Get composer cache directory
      id: composer-cache
      run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
      
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ runner.os }}-php-
        
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-dev
      
    - name: Build assets (if using Laravel Mix)
      run: |
        npm ci
        npm run production
      env:
        NODE_ENV: production
        
    - name: Create deployment package
      run: |
        # Exclude unnecessary files
        rm -rf .git
        rm -rf node_modules
        rm -rf tests
        rm -rf .github
        rm -rf .vscode
        rm -f .env.example
        rm -f .gitignore
        rm -f .gitattributes
        rm -f .styleci.yml
        rm -f phpunit.xml
        rm -f webpack.mix.js
        rm -f package.json
        rm -f package-lock.json
        
        # Create deployment package
        zip -r deployment-package.zip . -x "*.git*" "node_modules/*" "tests/*" ".github/*" ".vscode/*"
        
    - name: Deploy to RumahWeb via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./
        server-dir: /public_html/
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/tests/**
          **/.github/**
          **/.vscode/**
          **/.env.example
          **/.gitignore
          **/.gitattributes
          **/.styleci.yml
          **/phpunit.xml
          **/webpack.mix.js
          **/package.json
          **/package-lock.json
          **/README.md
          **/README_DASHBOARD.md
          **/DASHBOARD_MODERN_README.md
          **/PANDUAN_HOSTING_RUMAHWEB.md
          **/CHECKLIST_HOSTING_RUMAHWEB.md
          **/RINGKASAN_HOSTING.md
          **/config-hosting.env
          
    - name: Run post-deployment commands
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/${{ secrets.SSH_USERNAME }}/public_html
          
          # Set proper permissions
          chmod -R 755 storage/
          chmod -R 755 bootstrap/cache/
          chmod 644 .env
          
          # Clear caches
          php artisan config:clear
          php artisan cache:clear
          php artisan view:clear
          php artisan route:clear
          
          # Run migrations (if needed)
          # php artisan migrate --force
          
          echo "Deployment completed successfully!"
