name: Test FTP Connection

on:
  workflow_dispatch:

jobs:
  test-ftp:
    runs-on: ubuntu-latest
    
    steps:
    - name: Test FTP Connection
      run: |
        echo "🔍 Testing FTP connection details..."
        echo "=================================="
        echo "Server: '${{ secrets.FTP_SERVER }}'"
        echo "Username: '${{ secrets.FTP_USERNAME }}'"
        echo "Password: [HIDDEN - length: ${#FTP_PASSWORD}]"
        echo "=================================="
        
        # Check if secrets are set
        if [ -z "${{ secrets.FTP_SERVER }}" ]; then
          echo "❌ FTP_SERVER is not set!"
          exit 1
        fi
        
        if [ -z "${{ secrets.FTP_USERNAME }}" ]; then
          echo "❌ FTP_USERNAME is not set!"
          exit 1
        fi
        
        if [ -z "${{ secrets.FTP_PASSWORD }}" ]; then
          echo "❌ FTP_PASSWORD is not set!"
          exit 1
        fi
        
        echo "✅ All secrets are configured!"
        echo ""
        echo "🔗 Testing connection to: ${{ secrets.FTP_SERVER }}"
        echo "👤 Username: ${{ secrets.FTP_USERNAME }}"
        echo ""
        echo "📋 Next step: Check if these credentials work in deployment"
        
    - name: Success message
      run: |
        echo "🎉 FTP secrets test completed!"
        echo "If you see this, secrets are configured correctly."
        echo ""
        echo "💡 If deployment still fails, check:"
        echo "1. Password has no extra spaces"
        echo "2. Username is correct (invy5647)"
        echo "3. Server is correct (ftp.inventaris-min3.my.id)"
