name: Test GitHub Secrets

on:
  push:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Test FTP Server
      run: |
        echo "Testing FTP connection..."
        echo "FTP_SERVER: ${{ secrets.FTP_SERVER }}"
        echo "FTP_USERNAME: ${{ secrets.FTP_USERNAME }}"
        echo "FTP_PASSWORD: [HIDDEN]"
        
        if [ -z "${{ secrets.FTP_SERVER }}" ]; then
          echo "❌ FTP_SERVER is not set!"
          exit 1
        fi
        
        if [ -z "${{ secrets.FTP_USERNAME }}" ]; then
          echo "❌ FTP_USERNAME is not set!"
          exit 1
        fi
        
        if [ -z "${{ secrets.FTP_PASSWORD }}" ]; then
          echo "❌ FTP_PASSWORD is not set!"
          exit 1
        fi
        
        echo "✅ All secrets are configured!"
        
    - name: Success message
      run: |
        echo "🎉 GitHub Secrets test passed!"
        echo "Ready for deployment!"
