name: Test FTP Connection

on:
  workflow_dispatch:

jobs:
  test-ftp:
    runs-on: ubuntu-latest
    
    steps:
    - name: Test FTP Connection
      run: |
        echo "Testing FTP connection..."
        echo "Server: ${{ secrets.FTP_SERVER }}"
        echo "Username: ${{ secrets.FTP_USERNAME }}"
        echo "Password: [HIDDEN]"
        
        if [ -z "${{ secrets.FTP_SERVER }}" ]; then
          echo "❌ FTP_SERVER is not set!"
          exit 1
        fi
        
        if [ -z "${{ secrets.FTP_USERNAME }}" ]; then
          echo "❌ FTP_USERNAME is not set!"
          exit 1
        fi
        
        if [ -z "${{ secrets.FTP_PASSWORD }}" ]; then
          echo "❌ FTP_PASSWORD is not set!"
          exit 1
        fi
        
        echo "✅ All secrets are configured!"
        echo "Testing connection to: ${{ secrets.FTP_SERVER }}"
        
    - name: Success message
      run: |
        echo "🎉 FTP secrets test completed!"
        echo "If you see this, secrets are configured correctly."
